* Environment 
- Ubuntu 22.04.2

* Prerequisites

** Antlr CPP Runtime binary

This was the antlr4-cpp-runtime library used to build this project: https://www.antlr.org/download/antlr4-cpp-runtime-4.12.0-source.zip

Here is the tutorial to get it up and running on ubuntu: https:https://www.cs.sjsu.edu/~mak/tutorials/InstallANTLR4Cpp.pdf

All that is needed is the commands in `Download and install the C++ runtime for ANTLR` its subsection `Ubuntu installation` 


** Clang++ compiler:

Recommended: Ubuntu clang version 14.0.0-1ubuntu1

You will need `clang++>=14.0.0` to run this project. 

* Installation
To install the ANTLR4-generated scanner, follow these steps:

1. Download or clone the source code for the scanner.

2. Open a terminal and navigate to the directory where the source code is located.

3. Run the make command to compile the scanner code.

#+begin_src shell
make 
#+end_src

4. If the compilation is successful, the scanner executable will be

#+begin_src shell
./parser 
#+end_src

* Usage
To use the scanner, follow these steps:

1. Create a text file containing the input text to be scanned.
2. Open a terminal and navigate to the directory where the scanner executable is located.
3. Run the scanner executable, passing the input file as a command-line argument. For example:

#+begin_src 
./parser 
#+end_src

** Test Case 
The input is determined by the file [[file:test-in.txt]]. The scanner will read the input file and output the tokens it recognizes to the console. Simply change [[file:test-in.txt]] for the *master text case*
